data <- read.table("household_power_consumption.txt",sep=";",header=TRUE)
data<-subset(data,Date == "1/2/2007" | Date == "2/2/2007")
data$DateTime<-as.POSIXct(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
png("Plot2.png",bg="transparent")
plot(data$DateTime,as.numeric(as.character(data$Global_active_power)),type="n",xlab="",ylab="Global Active Power (kilowatts)")
lines(data$DateTime,as.numeric(as.character(data$Global_active_power)))
dev.off()